apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller-role
rules:
- apiGroups: ["autoscaling"]
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: controller-rolebinding
subjects:
- kind: ServiceAccount
  name: controller-sa
  namespace: default
roleRef:
  kind: ClusterRole
  name: controller-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: autoscaling-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autoscaling-controller
  template:
    metadata:
      labels:
        app: autoscaling-controller
    spec:
      serviceAccountName: controller-sa
      containers:
      - name: controller
        image: isp-controller:v1
        imagePullPolicy: Never
        env:
        - name: PROMETHEUS_URL
          value: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"
        - name: ML_SERVICE_URL
          value: "http://ml-prediction-service.default.svc.cluster.local:80"
        - name: CHECK_INTERVAL
          value: "60"
        - name: MIN_REPLICAS
          value: "2"
        - name: MAX_REPLICAS
          value: "10"
